import SideNav from '@/cmps/SideNav'
import Head from 'next/head'

import styles from '../styles/pages/_explore.module.scss'

export default function Explore() {
  return (
    <>
      <Head>
        <title>explore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.explore}>
        <SideNav />
      </main>
    </>
  )
}
