import Head from 'next/head'
import styles from '../styles/pages/Home.module.scss'
// import { useEffect, useState } from 'react'
import logo from '../../public/Disney+_logo.svg'
import Image from 'next/image'

export default function Home() {
  // const [res, setRes] = useState(null)

  // const load = async () => {
  //   // top rated
  //   // const res = await fetch(
  //   //   'https://api.themoviedb.org/3/movie/top_rated?api_key=b32d3cdb082983f9721d6e0cf0975d67&language=en-US&page=1'
  //   // )
  //   // genere list
  //   // const res = await fetch(
  //   //   'https://api.themoviedb.org/3/genre/movie/list?api_key=b32d3cdb082983f9721d6e0cf0975d67&language=en-US'
  //   // )
  //   // const m = await res.json()
  //   // console.log(m)
  // }
  // useEffect(() => {
  //   load()
  // }, [])

  return (
    <>
      <Head>
        <title>Diseny+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <section className={styles['landing-page']}>
          <header>
            <span className={styles['login-btn']}>
              <button>Log In</button>
            </span>
            <span className={styles.language}>
              <p>Choose language</p>
              <select name="" id="">
                <option value="">English</option>
                <option value="">Hebrew</option>
              </select>
            </span>
          </header>
          <div className={styles.container}>
            <div>
              <span>
                <Image src={logo} alt="" />
              </span>
              <p> + More than you&apos;d ever imagine </p>
              <div>
                <button>Sign Up Now</button>
                <span>&gt;</span>
              </div>
            </div>
          </div>
        </section>

        <div className={styles.divider}></div>

        <section className={styles['grid-container']}>
          <div>
            <span className="logo">logo</span>
            <h2>The greatest stories ever told</h2>
            <h3>
              Explore thousands of hours of TV series, movies and originals,
              from all the wonderful worlds of Disney+.
            </h3>
          </div>
          <div>
            <span className="logo">logo</span>
            <h2>Available on selected devices</h2>
            <h3>Stream on up to four screens at once on compatible devices.</h3>
          </div>
          <div>
            <span className="logo">logo</span>
            <h2>Easy-to-use parental controls</h2>
            <h3>Keep your family safe with our intuitive parental controls.</h3>
          </div>
        </section>
      </main>
    </>
  )
}

// https://image.tmdb.org/t/p/original/

// GET movie/top_rated
const topRated = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
      genre_ids: [18, 80],
      id: 238,
      original_language: 'en',
      original_title: 'The Godfather',
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      popularity: 112.806,
      poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
      release_date: '1972-03-14',
      title: 'The Godfather',
      video: false,
      vote_average: 8.7,
      vote_count: 17512,
    },
    {
      adult: false,
      backdrop_path: '/ejniJnlOdtSgtbh8D7u2RxT6Uli.jpg',
      genre_ids: [35, 14],
      id: 772071,
      original_language: 'es',
      original_title: 'Cuando Sea Joven',
      overview:
        '70-year-old Malena gets a second chance at life when she magically turns into her 22-year-old self. Now, posing as "Maria" to hide her true identity, she becomes the lead singer of her grandson\'s band and tries to recover her dream of singing, which she had to give up at some point.',
      popularity: 60.613,
      poster_path: '/6gIJuFHh5Lj4dNaPG3TzIMl7L68.jpg',
      release_date: '2022-09-14',
      title: 'Cuando Sea Joven',
      video: false,
      vote_average: 8.7,
      vote_count: 206,
    },
    {
      adult: false,
      backdrop_path: '/wPU78OPN4BYEgWYdXyg0phMee64.jpg',
      genre_ids: [18, 80],
      id: 278,
      original_language: 'en',
      original_title: 'The Shawshank Redemption',
      overview:
        'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
      popularity: 92.417,
      poster_path: '/hBcY0fE9pfXzvVaY4GKarweriG2.jpg',
      release_date: '1994-09-23',
      title: 'The Shawshank Redemption',
      video: false,
      vote_average: 8.7,
      vote_count: 23349,
    },
    {
      adult: false,
      backdrop_path: '/wxaBkuqVIgImjRHEMJoxL9Lq6i8.jpg',
      genre_ids: [16, 10751, 12, 14],
      id: 995133,
      original_language: 'en',
      original_title: 'The Boy, the Mole, the Fox and the Horse',
      overview:
        'The unlikely friendship of a boy, a mole, a fox and a horse traveling together in the boy’s search for home.',
      popularity: 37.08,
      poster_path: '/oQRgyQCzcyZvE6w5heM9ktVY0LT.jpg',
      release_date: '2022-12-25',
      title: 'The Boy, the Mole, the Fox and the Horse',
      video: false,
      vote_average: 8.6,
      vote_count: 234,
    },
    {
      adult: false,
      backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
      genre_ids: [18, 80],
      id: 240,
      original_language: 'en',
      original_title: 'The Godfather Part II',
      overview:
        'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
      popularity: 81.907,
      poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
      release_date: '1974-12-20',
      title: 'The Godfather Part II',
      video: false,
      vote_average: 8.6,
      vote_count: 10603,
    },
    {
      adult: false,
      backdrop_path: '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: 'en',
      original_title: "Schindler's List",
      overview:
        'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
      popularity: 57.507,
      poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
      release_date: '1993-12-15',
      title: "Schindler's List",
      video: false,
      vote_average: 8.6,
      vote_count: 13796,
    },
    {
      adult: false,
      backdrop_path: '/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg',
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: 'hi',
      original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
      overview:
        'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
      popularity: 22.588,
      poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
      release_date: '1995-10-19',
      title: 'Dilwale Dulhania Le Jayenge',
      video: false,
      vote_average: 8.6,
      vote_count: 4064,
    },
    {
      adult: false,
      backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: 'ja',
      original_title: '千と千尋の神隠し',
      overview:
        'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
      popularity: 93.588,
      poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
      release_date: '2002-09-20',
      title: 'Spirited Away',
      video: false,
      vote_average: 8.5,
      vote_count: 13984,
    },
    {
      adult: false,
      backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
      genre_ids: [18],
      id: 389,
      original_language: 'en',
      original_title: '12 Angry Men',
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 45.183,
      poster_path: '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
      release_date: '1957-04-10',
      title: '12 Angry Men',
      video: false,
      vote_average: 8.5,
      vote_count: 7064,
    },
    {
      adult: false,
      backdrop_path: '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
      genre_ids: [10749, 16, 18],
      id: 372058,
      original_language: 'ja',
      original_title: '君の名は。',
      overview:
        'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
      popularity: 100.711,
      poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
      release_date: '2016-08-26',
      title: 'Your Name.',
      video: false,
      vote_average: 8.5,
      vote_count: 9540,
    },
    {
      adult: false,
      backdrop_path: '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: 'ko',
      original_title: '기생충',
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 84.159,
      poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
      release_date: '2019-05-30',
      title: 'Parasite',
      video: false,
      vote_average: 8.5,
      vote_count: 15309,
    },
    {
      adult: false,
      backdrop_path: '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: 'en',
      original_title: 'The Green Mile',
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 95.825,
      poster_path: '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
      release_date: '1999-12-10',
      title: 'The Green Mile',
      video: false,
      vote_average: 8.5,
      vote_count: 15088,
    },
    {
      adult: false,
      backdrop_path: '/pbEkjhdfP7yuDcMB78YEZwgD4IN.jpg',
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: 'en',
      original_title: 'The Dark Knight',
      overview:
        'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
      popularity: 83.379,
      poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      release_date: '2008-07-14',
      title: 'The Dark Knight',
      video: false,
      vote_average: 8.5,
      vote_count: 29235,
    },
    {
      adult: false,
      backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
      genre_ids: [53, 80],
      id: 680,
      original_language: 'en',
      original_title: 'Pulp Fiction',
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 73.09,
      poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
      release_date: '1994-09-10',
      title: 'Pulp Fiction',
      video: false,
      vote_average: 8.5,
      vote_count: 24717,
    },
    {
      adult: false,
      backdrop_path: '/eoCSp75lxatmIa6aGqfnzwtbttd.jpg',
      genre_ids: [37],
      id: 429,
      original_language: 'it',
      original_title: 'Il buono, il brutto, il cattivo',
      overview:
        'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
      popularity: 76.861,
      poster_path: '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
      release_date: '1966-12-23',
      title: 'The Good, the Bad and the Ugly',
      video: false,
      vote_average: 8.5,
      vote_count: 7227,
    },
    {
      adult: false,
      backdrop_path: '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: 'en',
      original_title: 'Forrest Gump',
      overview:
        'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
      popularity: 72.514,
      poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
      release_date: '1994-06-23',
      title: 'Forrest Gump',
      video: false,
      vote_average: 8.5,
      vote_count: 24205,
    },
    {
      adult: false,
      backdrop_path: '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: 'en',
      original_title: 'The Lord of the Rings: The Return of the King',
      overview:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      popularity: 83.763,
      poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
      release_date: '2003-12-01',
      title: 'The Lord of the Rings: The Return of the King',
      video: false,
      vote_average: 8.5,
      vote_count: 21192,
    },
    {
      adult: false,
      backdrop_path: '/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg',
      genre_ids: [10749, 16],
      id: 372754,
      original_language: 'ja',
      original_title: '同級生',
      overview:
        'Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.',
      popularity: 14.837,
      poster_path: '/cIfRCA5wEvj9tApca4UDUagQEiM.jpg',
      release_date: '2016-02-20',
      title: 'Dou kyu sei – Classmates',
      video: false,
      vote_average: 8.5,
      vote_count: 291,
    },
    {
      adult: false,
      backdrop_path: '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
      genre_ids: [10749],
      id: 696374,
      original_language: 'en',
      original_title: "Gabriel's Inferno",
      overview:
        "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
      popularity: 17.747,
      poster_path: '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
      release_date: '2020-05-29',
      title: "Gabriel's Inferno",
      video: false,
      vote_average: 8.5,
      vote_count: 2325,
    },
    {
      adult: false,
      backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
      genre_ids: [18, 80],
      id: 769,
      original_language: 'en',
      original_title: 'GoodFellas',
      overview:
        'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
      popularity: 52.174,
      poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
      release_date: '1990-09-12',
      title: 'GoodFellas',
      video: false,
      vote_average: 8.5,
      vote_count: 11016,
    },
  ],
  total_pages: 543,
  total_results: 10844,
}

// /genre/movie/list
const genereList = {
  genres: [
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 12,
      name: 'Adventure',
    },
    {
      id: 16,
      name: 'Animation',
    },
    {
      id: 35,
      name: 'Comedy',
    },
    {
      id: 80,
      name: 'Crime',
    },
    {
      id: 99,
      name: 'Documentary',
    },
    {
      id: 18,
      name: 'Drama',
    },
    {
      id: 10751,
      name: 'Family',
    },
    {
      id: 14,
      name: 'Fantasy',
    },
    {
      id: 36,
      name: 'History',
    },
    {
      id: 27,
      name: 'Horror',
    },
    {
      id: 10402,
      name: 'Music',
    },
    {
      id: 9648,
      name: 'Mystery',
    },
    {
      id: 10749,
      name: 'Romance',
    },
    {
      id: 878,
      name: 'Science Fiction',
    },
    {
      id: 10770,
      name: 'TV Movie',
    },
    {
      id: 53,
      name: 'Thriller',
    },
    {
      id: 10752,
      name: 'War',
    },
    {
      id: 37,
      name: 'Western',
    },
  ],
}
