import Head from 'next/head'

export default function Shows() {
  return (
    <>
      <Head>
        <title>Videoplus - Shows</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Shows</h1>
      </main>
    </>
  )
}
